//! Браузеры: выборочные сайты через мост, остальное напрямую (PAC-файл).
//!
//! Зачем PAC: браузеры (Chrome/Edge/Firefox) игнорируют HTTP_PROXY env — им
//! нужен либо флаг --proxy-server на весь трафик, либо системный PAC-скрипт.
//! PAC даёт то, чего не может мост сам: решение «этот сайт — через прокси,
//! остальные — с реальным IP» принимается ДО открытия соединения, прямо в
//! браузере. Мост при этом продолжает свою доменную маршрутизацию: сайт из
//! white-списка ушёл в PROXY 127.0.0.1:8889 → мост решил anthropic.com →
//! внешний прокси, всё остальное → дефолт.
//!
//! Механика: пишем astreya-gate.pac в папку настроек и прописываем его как
//! AutoConfigURL в HKCU\...\Internet Settings (User scope — прав администратора
//! НЕ требует). Chrome/Edge читают системный прокси автоматически; Firefox —
//! в режиме «использовать системные настройки» (дефолт). Чужие настройки
//! (ProxyEnable/ProxyServer/чужой AutoConfigURL) сохраняем перед перезаписью и
//! возвращаем при выключении — тот же контракт, что у env_proxy для env.
//!
//! После правки реестра рассылаем WinINET InternetSetOption(SETTINGS_CHANGED/
//! REFRESH) — иначе открытые браузеры узнают о смене только после перезапуска.

use serde::Serialize;

/// Порт моста — переиспользуем константу шима (единая точка правды).
use crate::shim::LISTEN_PORT;

const REG_PATH: &str = r"HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings";
/// Ключи-снимок: что мы могли перезаписать и обязаны вернуть при disable().
const SNAPSHOT_KEYS: &[&str] = &["AutoConfigURL", "ProxyEnable", "ProxyServer"];

// ─── Модель правил ───────────────────────────────────────────────

/// Режим списка сайтов.
///
/// Whitelist («список через прокси») — безопасный дефолт: забыли добавить
/// сайт → он ходит напрямую с реальным IP, ничего не ломается. Blacklist —
/// строгий: ВСЁ через прокси, кроме перечисленного; забытый сайт уедет в
/// мост (и дальше по его правилам), а не наружу.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PacMode {
    Whitelist,
    Blacklist,
}

impl PacMode {
    #[allow(dead_code)] // пригодится при логировании режима в будущих правках
    pub fn as_str(self) -> &'static str {
        match self {
            PacMode::Whitelist => "whitelist",
            PacMode::Blacklist => "blacklist",
        }
    }
    pub fn from_str(s: &str) -> Self {
        if s.eq_ignore_ascii_case("blacklist") {
            PacMode::Blacklist
        } else {
            PacMode::Whitelist
        }
    }
}

/// Сгенерировать JS PAC-файла. Только ES5: движок JScript в WinINET старый,
/// стрелочных функций/endsWith там нет — скрипт обязан парситься везде.
fn build_pac_js(mode: PacMode, sites: &[String]) -> String {
    let list = sites
        .iter()
        .map(|d| format!("    {}", serde_json::json!(d.to_ascii_lowercase())))
        .collect::<Vec<_>>()
        .join(",\n");
    // shExpMatch(host, "*.d") покрывает поддомены, shExpMatch(host, d) — сам
    // домен. Это ровно та же семантика суффикс-матча, что у моста.
    let proxy = format!("PROXY 127.0.0.1:{LISTEN_PORT}");
    let body = match mode {
        PacMode::Whitelist => format!(
            r#"  var listed = shExpMatchList(host);
  if (listed) return "{proxy}";
  return "DIRECT";"#
        ),
        PacMode::Blacklist => format!(
            r#"  var listed = shExpMatchList(host);
  if (listed) return "DIRECT";
  return "{proxy}";"#
        ),
    };
    format!(
        r#"// Generated by Astreya Gate — не редактируйте вручную:
// изменения перезаписываются приложением при сохранении настроек.
var SITES = [
{list}
];

function shExpMatchList(host) {{
  for (var i = 0; i < SITES.length; i++) {{
    var d = SITES[i];
    if (shExpMatch(host, d) || shExpMatch(host, "*." + d)) return true;
  }}
  return false;
}}

function FindProxyForURL(url, host) {{
  host = (host || "").toLowerCase();
{body}
}}"#
    )
}

/// Записать PAC-файл в папку настроек. Возвращает путь к нему.
pub fn write_pac(mode: PacMode, sites: &[String]) -> Result<std::path::PathBuf, String> {
    let dir = dirs::config_dir()
        .ok_or_else(|| "Не нашёл папку %APPDATA%".to_string())?
        .join("Astreya Gate");
    std::fs::create_dir_all(&dir).map_err(|e| format!("create dir {}: {e}", dir.display()))?;
    let path = dir.join("astreya-gate.pac");
    let js = build_pac_js(mode, sites);
    std::fs::write(&path, js).map_err(|e| format!("write {}: {e}", path.display()))?;
    Ok(path)
}

// ─── Реестр / системное состояние ────────────────────────────────

/// Что реально прописано в системных настройках прокси Windows (HKCU).
#[derive(Debug, Clone, Serialize, Default)]
pub struct SystemProxyState {
    #[serde(rename = "autoConfigUrl")]
    pub auto_config_url: Option<String>,
    pub proxy_enable: Option<String>,
    pub proxy_server: Option<String>,
}

pub fn read_system() -> SystemProxyState {
    let script = format!(
        "$p = Get-ItemProperty -Path '{REG_PATH}' -ErrorAction SilentlyContinue; \
         Write-Output ('ACU:' + $p.AutoConfigURL); \
         Write-Output ('PEN:' + $p.ProxyEnable); \
         Write-Output ('PSV:' + $p.ProxyServer);"
    );
    let out = crate::tasks::run_ps_public(&script).unwrap_or_default();
    let mut st = SystemProxyState::default();
    for line in out.lines() {
        let mut it = line.splitn(2, ':');
        let (k, v) = match (it.next(), it.next()) {
            (Some(k), Some(v)) => (k.trim(), v.trim()),
            _ => continue,
        };
        // Get-ItemProperty отсутствующий ключ отдаёт пустой строкой.
        let val = (!v.is_empty()).then(|| v.to_string());
        match k {
            "ACU" => st.auto_config_url = val,
            "PEN" => st.proxy_enable = val,
            "PSV" => st.proxy_server = val,
            _ => {}
        }
    }
    st
}

/// Указывает ли системный AutoConfigURL на НАШ pac-файл.
fn is_ours(acu: Option<&str>) -> bool {
    acu.map(|u| u.contains("astreya-gate.pac")).unwrap_or(false)
}

/// file:// URL с экранированными пробелами — формат, который WinINET ест.
fn file_url(path: &std::path::Path) -> String {
    format!("file:///{}", path.to_string_lossy().replace('\\', "/").replace(' ', "%20"))
}

/// Сохранить чужие значения перед перезаписью (для возврата при disable).
fn snapshot_foreign(st: &SystemProxyState) {
    let mut m = std::collections::HashMap::new();
    if let Some(v) = &st.auto_config_url {
        m.insert("AutoConfigURL".into(), v.clone());
    }
    if let Some(v) = &st.proxy_enable {
        m.insert("ProxyEnable".into(), v.clone());
    }
    if let Some(v) = &st.proxy_server {
        m.insert("ProxyServer".into(), v.clone());
    }
    let _ = crate::settings::set_saved_browser_proxy(if m.is_empty() { None } else { Some(m) });
}

/// Прописать наш PAC системным прокси. Порядок свят: сначала снимок чужого,
/// затем ProxyEnable=0 + чистка ProxyServer (иначе Chromium путается в двух
/// источниках), потом AutoConfigURL, потом WinINET-refresh.
pub fn enable() -> Result<(), String> {
    let s = crate::settings::load();
    let mode = PacMode::from_str(s.browser_mode.as_deref().unwrap_or("whitelist"));
    let path = write_pac(mode, &s.browser_sites)?;
    let before = read_system();
    if !is_ours(before.auto_config_url.as_deref()) {
        snapshot_foreign(&before);
    }
    let acu = file_url(&path);
    let script = format!(
        "Set-ItemProperty -Path '{REG_PATH}' -Name ProxyEnable -Value 0 -Type DWord; \
         Remove-ItemProperty -Path '{REG_PATH}' -Name ProxyServer -ErrorAction SilentlyContinue; \
         New-ItemProperty -Path '{REG_PATH}' -Name AutoConfigURL -Value '{acu}' -PropertyType String -Force | Out-Null; \
         Write-Output 'PAC_SET'",
        acu = acu.replace('\'', "''"),
    );
    let out = crate::tasks::run_ps_public(&script)
        .ok_or_else(|| "powershell.exe не выполнил запись AutoConfigURL".to_string())?;
    if !out.contains("PAC_SET") {
        return Err(format!("Не удалось включить PAC: {out}"));
    }
    notify_wininet();
    Ok(())
}

/// Убрать наш PAC; вернуть чужие настройки, если мы их перезаписывали.
pub fn disable() -> Result<(), String> {
    let saved = crate::settings::load().saved_browser_proxy.unwrap_or_default();
    let mut script = String::from(
        "Remove-ItemProperty -Path 'REG' -Name AutoConfigURL -ErrorAction SilentlyContinue; ",
    )
    .replace("REG", REG_PATH);
    for key in SNAPSHOT_KEYS.iter().skip(1) {
        match saved.get(*key) {
            Some(v) => script.push_str(&format!(
                "Set-ItemProperty -Path '{REG_PATH}' -Name '{key}' -Value '{}' -Force; ",
                v.replace('\'', "''"),
            )),
            None => script.push_str(&format!(
                "Remove-ItemProperty -Path '{REG_PATH}' -Name '{key}' -ErrorAction SilentlyContinue; ",
            )),
        }
    }
    script.push_str("Write-Output 'PAC_CLEARED'");
    let out = crate::tasks::run_ps_public(&script)
        .ok_or_else(|| "powershell.exe не выполнил очистку AutoConfigURL".to_string())?;
    if !out.contains("PAC_CLEARED") {
        return Err(format!("Не удалось выключить PAC: {out}"));
    }
    notify_wininet();
    Ok(())
}

/// WinINET: сообщить приложениям об изменении настроек прокси (без этого
/// уже запущенные браузеры живут со старым конфигом до перезапуска).
fn notify_wininet() {
    let script = "\
       $sig = '[DllImport(\"wininet.dll\", SetLastError=true)] public static extern bool InternetSetOption(IntPtr h, int opt, IntPtr buf, int len);'; \
       $t = Add-Type -MemberDefinition $sig -Name W -Namespace P -PassThru; \
       $t::InternetSetOption([IntPtr]::Zero, 39, [IntPtr]::Zero, 0) | Out-Null; \
       $t::InternetSetOption([IntPtr]::Zero, 37, [IntPtr]::Zero, 0) | Out-Null; \
       Write-Output 'NOTIFIED'";
    let _ = crate::tasks::run_ps_public(&format!(
        "[Console]::OutputEncoding=[System.Text.Encoding]::UTF8; {script}"
    ));
}

// ─── Статус для UI ───────────────────────────────────────────────

#[derive(Debug, Clone, Serialize)]
pub struct BrowserStatus {
    /// Наш PAC сейчас прописан системным? (по факту реестра)
    pub active: bool,
    /// Текущий системный AutoConfigURL (если не наш — покажем чужой).
    pub system_auto_config_url: Option<String>,
    /// Настройки пользователя (режим + список).
    pub mode: String,
    pub sites: Vec<String>,
    /// Путь к генерируемому pac-файлу (для «открыть папку»).
    pub pac_path: Option<String>,
}

pub fn status() -> BrowserStatus {
    let sys = read_system();
    let s = crate::settings::load();
    BrowserStatus {
        active: is_ours(sys.auto_config_url.as_deref()),
        system_auto_config_url: sys.auto_config_url,
        mode: s.browser_mode.unwrap_or_else(|| "whitelist".into()),
        sites: s.browser_sites,
        pac_path: dirs::config_dir()
            .map(|d| d.join("Astreya Gate").join("astreya-gate.pac"))
            .map(|p| p.to_string_lossy().to_string()),
    }
}
